---
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
script:
  - python setup.py test -a --cov=eip712_structs
services:
  - docker
before_install:
  - docker-compose up -d
after_success:
  - coveralls
